version: "3.8"
services:
  front:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
    volumes:
      - ./front/src:/srv/www
      - ./front/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
