version: "3.8"
services:
  front:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./front/src:/srv/www
      - /source/challenge_mount:/srv/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
      - ./front/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  back:
    image: python
    ports:
      - 8080:8080
    volumes:
      - ./back:/srv/www
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    command: "/bin/sh -c 'cd srv/www/ && pip install -r ./requirements.txt && flask --app main run --port 8080'"

