name: deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  DESTINATION_DIR: /srv/www/sglazkov.pro

jobs:
  deploy-html-nginxconf:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: sglazkov.pro
          username: ${{ secrets.SGLAZKOVPRO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /source/sglazkov.pro/
            sudo git pull

  docker_start:
    needs: [deploy-html-nginxconf]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: sglazkov.pro
          username: ${{ secrets.SGLAZKOVPRO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo -s
            docker-compose -f /source/sglazkov.pro/docker-compose.yml pull
            docker-compose -f /source/sglazkov.pro/docker-compose.yml down
            docker-compose -f /source/sglazkov.pro/docker-compose.yml up -d
