name: deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  DESTINATION_DIR: /srv/www/sglazkov.pro

jobs:
  deploy-html-nginxconf:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: sglazkov.pro
          username: ${{ secrets.SGLAZKOVPRO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /source
            git clone git@github.com:glsglsgls/sglazkov.pro.git
            nginx -s reload

  docker_start:
    needs: [deploy-html-nginxconf]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: sglazkov.pro
          username: ${{ secrets.SGLAZKOVPRO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker-compose -f ${{ env.DESTINATION_DIR }}/docker-compose.yml pull
            docker-compose -f ${{ env.DESTINATION_DIR }}/docker-compose.yml down
            docker-compose -f ${{ env.DESTINATION_DIR }}/docker-compose.yml up -d
